services:
  ros:
    build:
      context: ../
      dockerfile: simulator/Dockerfile
    runtime: nvidia
    environment:
      - DISPLAY=:0
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - PYTHONUNBUFFERED=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    command: bash -c "
      ros2 run turtlesim turtlesim_node &
      xterm -e ros2 run turtlesim turtle_teleop_key"